### PR TITLE
Ensemble generalisation and evaluator threading

### PR DESCRIPTION
**Pull request by James-Large**
Main questions are: Jay/Tony happy with the HiveCote layout? How do we want to standardise threading codebase-wide?

* AbstractEnsemble: Pulled 90% of the code out of CAWPE and put it into an abstract base class. Has the abstract method setupDefaultSettings(), called in the constructor, that all extending ensembles need to implement. 
  * CAWPE has that as an example, and hivecote 's been re-implemented using this schema, see [HIVE_COTE](https://github.com/uea-machine-learning/uea-tsc/blob/ensembleGeneralisation/src/main/java/weka_uea/classifiers/ensembles/HIVE_COTE.java). If people are happy with this general approach, obviously then needs to be moved to timeseriesweka/classifiers/hybrids/, javadoc and author tags to be updated, and Jay/Tony to review the default settings (e.g. rise/crise, boss/rboss etc) and possibly add extra setup funcs for old/new versions etc. 
  * AbstractEnsemble has a super basic threading scheme when training, un-optimised but still speed up of about 4x with 8 threads in basic testing, basic cawpe small datasets
  * AbstractEnsemble is naively train contractable, very likely wont meet contract if any base classifiers are not themselves contractable or estimate their own train acc. Both could be overcome if wanted, but discussion on that needed and maybe we just enforce that both be true if you want the contract to mean anything on user. Contract also does not consider threading atm. 
  * Checkpointing still to do when massively wanted
* Evaluators tided up some more and the meta info in results objects tried to be auto-completed as much as possible, inheritance hierarchy expanded a bit, and the multi-sample evaluators (stratified resamples and cross validation) have been threaded

On threading, part of the reason for pushing this now alongside the hive-cote review, how do we want to do this codebase-wide? Having different objects at different 'levels' spawning and destroying their own threads doesn't sound great, E.g. experiments sets hivecote to multithread. Hivecote sets each base classifier to multithread. Each baseclassifier multithreads their components. Their components might also be threadable, etc.

1. I'm kind of leaning towards just doing no-brainer singleton executor service that everything 'submits its jobs' too and using futures to keep track of when your threads complete. If the singleton service is ever invoked, spawn the (e.g. 8) threads once, and then every multithreadable thing queues up to use those same threads. Have some limit/blocker on the queue at e.g. 50 jobs to prevent memory bloat, jobs a goodun? 

2. Alternatively, have as part of the multithreadble interface a setExecutor method so that different 'processes' can have their own thread pools they work with and pass around between each other. So not global, but accessible within some logical chunk of the program. E.g. say we give hivecote 20 threads, it spawns 5 threads with it's own service, one for each base classifier, then e.g. builds 5 new threadpools with 3 threads each to give to each classifier (assuming they themselves are multithreadble) to use as they see fit, passing around that service to any of their own components etc.

### CODE REVIEW

**Comment by TonyBagnall** [comment]
looking at it now, looks good. A few things:

1. Threading: I think you may have over complicated it from what I envisaged as a first go. I just wanted each ensemble member in its own thread as sensible default behaviour if you build the whole thing via one classifier. I'm not saying threading it all isnt desirable, its just not our use case (cluster wide) and therefore should not be a priority. (it may be that this is what the AbstractClassifier already does, and the rest is discussion, in which case, just leave it at that for now). 

2. I'm not sure we want the AbstractEnsemble contractable, since as you say its not really enforcable on all possible constituents. I think contractable is up to the sub classes

3. I also dont think AbstractEnsemble needs to be TrainAccuracyEstimator, as it has no special way of doing that. If its just CV, thats handled at the level above. I view  TrainAccuracyEstimator as a specialism that allows the classifier to define a bespoke way of doing it. 

4. Do we actually need the interface EnsembleModule? Can we not just have Classifiers, or AbstractClassifiers? IS it just to encapsulate the classifier names? I dont mind them being in a parallel array, I want to keep this slim if possible. 

5. At some level we want it to be contractable, but I think that is the responsibility of the subclass too.

**Comment by James-Large** [comment]
1. Yeah the exact threading behaviour is up for discussion. If all the base classifiers are TrainAccuracyEstimators and you give the ensemble at least as many threads as the number of classifiers, that's what it would do as written. Can enforce one thread per base classifier in any case and clone the evaluators for each non-TrainAccuracyEstimator classifier, e.g. do this: 

```
//spawn threads
for each module m 
    spawn thread Tm to do: { 
        if m is a trainAccEstimator
            m.buildclassifier (evaluates internally)
            trainResults = m.classifier.gettrainresults()
        else 
            clone trainEstimator
            trainResults = trainEstimator.evaluate(m)
            m.buildclassifier
        return trainResults
    }

//collect results
for each module m 
    wait for thread Tm to finish
    m.trainResults = Tm.result
```

Then that structure would be more extendable in future. The potential for trainAccEstimators was throwing me off and the need to clone the estimators to run in parallel, but I'll try implementing that structure now, is much better than what's there currently

Either way, that's behaviour for this ensemble, part of question was larger discussion on anything else we might want to thread. If everything potentially spawns/destroys it's own threads over and over with no communication, that's not going to end well. This can be delayed until really wanted (and threading only done in bespoke way here), but threading all the major stuff was requested a while ago 

Not sure what you mean by cluster wide use case in context of threading?

2. Sure, can leave that and checkpointable out for sub classes

3. It combines the train predictions (assumed to be aligned with the same estimation procedure) of the base classifiers, This is bespoke behaviour and much faster/cleaner than doing nested CV at a higher level. If the train predictions are not aligned (e..g. one classifier does internal bagging, another does internal cv), I'd argue that's for the implementing classes to override and fix

4. It's not a necessity to run things obviously, but not sure why you'd want to remove it? People using the ensembles dont interact with the EnsembleModule class at all, it's just a simple data type to keep information about different base classifiers together internally. If you mean slim as in the number of files, can probably just make it a nested class? 

5. 2

**Comment by TonyBagnall** [comment]
1. >Not sure what you mean by cluster wide use case in context of threading?
I just mean we dont thread or use these classifiers as one offs, we post process

3. >It combines the train predictions (assumed to be aligned with the same estimation procedure) 
I'm going to look exactly how it works now. 

4. >It's not a necessity to run things obviously, but not sure why you'd want to remove it? 
for the same reason I wanted to remove HiveCoteModule, I prefer to strip down the code base if we can its already a bit bloaty. But also, it makes the code less general. You cannot just build an ensemble of any old classifier.

**Comment by James-Large** [comment]
1. Ah fair. Sure, can delay the decisions, will tidy up what's there. Making these things threadable was largely desired for the public showcasing and/or usability, can delay bigger decisions 

2. see AbstractEnsemble.estimateEnsemblePerformance() 

3. It's not an interface, its a simple data container which has a classifier reference that can be of any type. Otherwise CAWPE couldn't build on e.g. weka's classifiers

**Comment by James-Large** [comment]
* Simplified the threading in abstractensemble
* Evaluators can now be cloned (with their settings) to aid higher-level threading also  (touched many files)
* Moved the contracting code from abstractensemble to the hive_cote extension of it
* Made it extend AbstractClassifierWithTrainingInfo
* Made AbstractClassifierWithTrainingInfo implement Randomizable for issue #111 and added a seed variable
* For classifiers already extending AbstractClassifierWithTrainingInfo, removed, any pre-existing int seed variable so that the one it now inherits is used  (touched many files)
* Ensemblemodule moved from own file to be nested class in abstractensemble (touched many files)

Ready to merge imo, and then tony or jay to 'finalise' the hive_cote extension of the abstractensemble to however they want it

**Comment by TonyBagnall** [comment]
ok great, I'll merge unless you want to wait?

**Pull request merged**
